### ISSUE TITLE
Configuration client crashes with error message

### ISSUE THREAD

**Issue by AAide** [ViGEm/HidHide#1]
How to solve this problem ?

![image](https://user-images.githubusercontent.com/77096798/113431422-0885b280-93dc-11eb-8bec-4ad73f4a758c.png)

**Comment by nefarius** [comment]
We are aware of the issue but don't know the cause nor a solution yet. Be patient.

**Comment by AAide** [comment]
Is the problem the same on the older versions? or is it because of new windows updates that the problem occurred?

**Comment by nefarius** [comment]
What do you mean "same as old version", this is literally the first release ever?

**Comment by AAide** [comment]
I just came across the software not even 1 hour ago after I was looking for a software that allows you to block peripherals in games and that they just take the keys configured in xpadder and I came across this wonders, but who is struggling at the moment.
I thought they had another version there, because I would have tried older versions to find out if they worked. Maybe if you undo the old modifications add to the code, it will work.

**Comment by nefarius** [comment]
This project was released literally 2 days ago, there exists no "older version" to go back to 😛

**Comment by AAide** [comment]
Ah I didn't know, I hope they will be available soon, because it interests me a lot, I arrived on your project from the page of https://github.com/ViGEm/HidGuardian.

HidGuardian has the same problem?

**Comment by nefarius** [comment]
> HidGuardian has the same problem?

HidGuardian is a completely different discontinued project that has nothing to do with this one.

**Comment by AAide** [comment]
Okay, in that case, I'll wait until hidhide is functional because it's essential for me. thanks for the quick responses.

**Comment by nefarius** [comment]
Are you by any chance using a Laptop?

**Comment by AAide** [comment]
No on a tower pc, I have a laptop pc, I will try it to see how it works and I will keep you posted

**Comment by nefarius** [comment]
I'm asking because we *think* it has something to do with touchpads.

**Comment by AAide** [comment]
I tried on a laptop, it has the same problem.
On my pc towers I had things plugged into usb, I removed everything and still the same problem .

**Comment by nefarius** [comment]
Yeah might not be so easy after all, on my Laptop it works too. We'll see.

**Comment by AAide** [comment]
I have my laptop with touch screen and my pc towers is connected to a 55 inch tv, I have another laptop under windows 7 without touch screen, I will try to see what happens

**Comment by nefarius** [comment]
Windows 7 is not supported so it won't install. Only Windows 10 x64.

**Comment by AAide** [comment]
Ok so I can do nothing else, I will wait for you to publish a new version with the bug fixed, but if I can help you with something, don't hesitate to ask me .

**Comment by nefarius** [comment]
Once we found it there shall be an update 😉

**Comment by Catnavido** [comment]
Hm ... I see under "%SystemRoot%\System32\Winevt\Logs\Nefarius-Drivers-HidHide%4Diagnostic.etl" that the logging and tracing contains more detailed information ... the message seems related to the top-level exception handler. More detailed information should be available in the Event Logger under "Application and Services Logs\Nefarius\Drivers\HidHide"provided that you enable "Show Analytic and Debug Logs" under "View" first. This information is rather valueble for the fault isolation, I guess.

**Comment by AAide** [comment]
in windows event viewer it always shows the same error when the error in hidhide occurs.

Exception at "src\HidHideClient.cpp" line 109 CHidHideClientApp::InitInstance CONFIGRET 0x00000025 at src\HidHideApi.cpp(207) `anonymous-namespace'::DeviceBaseContainerId: no such value

**Comment by nefarius** [comment]
CONFIGRET 0x00000025 evaluates to `CR_NO_SUCH_VALUE` 🤔

**Comment by Hubert365** [comment]
For the record, mine says that:

Exception at "src\HidHideClient.cpp" line 109 CHidHideClientApp::InitInstance Error code 0x0020 at src\HidHideApi.cpp(373) `anonymous-namespace'::HidModelInfo: The process cannot access the file because it is being used by another process.

**Comment by nefarius** [comment]
`ERROR_SHARING_VIOLATION`

**Comment by tonebacas** [comment]
If you're using DS4Windows, disable "Hide DS4 Controller". That solved this problem.

**Comment by AAide** [comment]
I am not DS4Windows, so the problem is elsewhere for me .

**Comment by Hubert365** [comment]
> 
> 
> If you're using DS4Windows, disable "Hide DS4 Controller". That solved this problem.

I'm using DS4W, but that option is unchecked. I also tried with DS4W closed and the crash still occurs.

**Comment by nefarius** [comment]
> I am not DS4Windows, so the problem is elsewhere for me .

[Please try this test build of the client](https://ci.appveyor.com/api/buildjobs/nxpb4lsgn1j7aldc/artifacts/bin%2FRelease%2Fx64%2FHidHideClient.exe), you still need to have the MSI installed but use thus application instead.

**Comment by AAide** [comment]
![image](https://user-images.githubusercontent.com/77096798/113449205-9a51e780-93fd-11eb-961b-9ab3efb93725.png)

Yes !!! That no longer makes the mistake. you're a boss, I just have to test the software to see if it does what it is supposed to work for, in any case thank you, you solved the main problem, hoping that 'there is no other :)

**Comment by Hubert365** [comment]
Fixed mine too even though it was a different error (but both had to do with that damn line 109, maybe? :P ), thanks Nef

![image](https://user-images.githubusercontent.com/79023565/113449528-0b78a700-93cc-11eb-9f6f-540b66a569fb.png)

**Comment by nefarius** [comment]
> Fixed mine too even though it was a different error (but both had to do with that damn line 109, maybe? :P ), thanks Nef
> 
> ![image](https://user-images.githubusercontent.com/79023565/113449528-0b78a700-93cc-11eb-9f6f-540b66a569fb.png)

Because we fixed both cases in the same go 😉

**Comment by AAide** [comment]
it was fixed in a few hours and I just tested it it's really perfect, it prevents applications from recognizing the device, I'm really happy because it's been a while since I was looking for a software that could do that and you created the best, simple and efficient, I just tested it on final fantasy 8 and on xpadder and when they are not in the list with the device locked, well they are simply not recognized by the games. Perfect nothing else to say.

**Comment by nefarius** [comment]
Fixed release is live!

**Comment by Dgrif12** [comment]
<img width="547" alt="hidhideerror" src="https://user-images.githubusercontent.com/19676456/124856562-59bfb800-df70-11eb-9f98-dafea7189204.PNG">
I am having the same error and I've followed all the instructions of the setup guide and everything mentioned here. I have not ran the test version, but I have run the latest build.
I am running on Windows x64 of Microsoft Surface Laptop 3.

**Comment by Dgrif12** [comment]
I am still having this issue on the same device even running the latest release. I've followed through the guides, installed the prerequisites, restarted, repaired, etc. I've tried disabling the anti-virus and the issue still persists. When the error occurs, this appears in Windows Event Viewer: "Exception at "src\HidHideClient.cpp" line 155 CHidHideClientApp::InitInstance Error code 0x0032 at \HID.cpp(286) `anonymous-namespace'::HidModelInfo: The request is not supported."
